## AI-Powered Educational Chatbot

In [ ]:
 STEP1 : Importing Library and Data Loading
 STEP2 : Data Cleaning
 STEP3 : Data Embedding and Model Deployment(Transformer)
 STEP4 : Cosine Similarity and Testing Model

## STEP1 : Importing Library and Data Loading

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('knowledge_base1.csv')

In [3]:
df.head()

,id,category,question,answer
0,1,Artificial Intelligence,What is Artificial Intelligence?,Artificial Intelligence (AI) is the field of c...
1,2,Artificial Intelligence,What is an AI agent?,An AI agent is a system that perceives its env...
2,3,Artificial Intelligence,What is supervised AI?,Supervised AI usually refers to AI systems tra...
3,4,Artificial Intelligence,What is weak AI?,"Weak AI, or narrow AI, is designed to perform ..."
4,5,Artificial Intelligence,What is artificial general intelligence?,Artificial General Intelligence (AGI) is a hyp...

In [4]:
df1 = df.copy()

In [5]:
df1.head()

,id,category,question,answer
0,1,Artificial Intelligence,What is Artificial Intelligence?,Artificial Intelligence (AI) is the field of c...
1,2,Artificial Intelligence,What is an AI agent?,An AI agent is a system that perceives its env...
2,3,Artificial Intelligence,What is supervised AI?,Supervised AI usually refers to AI systems tra...
3,4,Artificial Intelligence,What is weak AI?,"Weak AI, or narrow AI, is designed to perform ..."
4,5,Artificial Intelligence,What is artificial general intelligence?,Artificial General Intelligence (AGI) is a hyp...

## STEP2 : Data Cleaning

In [6]:
df1 = df1.drop(['id'],axis = 1)

In [7]:
df1 = df1.drop(['category'],axis = 1)

In [9]:
df1.shape ## It is total shape of whole dataset

(200, 2)

In [10]:
df1.isna().sum() ## It is predicting , there is no null value in this whole dataset.

question    0
answer      0
dtype: int64

In [11]:
df1.info() ## There is information about whole dataset.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   question  200 non-null    object
 1   answer    200 non-null    object
dtypes: object(2)
memory usage: 3.3+ KB

In [12]:
df1.duplicated().sum()  ## There is no duplicate value

0

In [13]:
import re

# Create a copy of the original dataset
df_clean = df1.copy()

# Convert question and answer to string
df_clean['question'] = df_clean['question'].astype(str)
df_clean['answer'] = df_clean['answer'].astype(str)

# Remove leading and trailing spaces
df_clean['question'] = df_clean['question'].str.strip()
df_clean['answer'] = df_clean['answer'].str.strip()

# Remove HTML tags
df_clean['question'] = df_clean['question'].str.replace(
    r'<[^>]+>', '', regex=True
)

df_clean['answer'] = df_clean['answer'].str.replace(
    r'<[^>]+>', '', regex=True
)

# Replace multiple spaces/newlines with a single space
df_clean['question'] = df_clean['question'].str.replace(
    r'\s+', ' ', regex=True
)

df_clean['answer'] = df_clean['answer'].str.replace(
    r'\s+', ' ', regex=True
)

# Remove duplicate question-answer pairs
df_clean = df_clean.drop_duplicates(
    subset=['question', 'answer']
).reset_index(drop=True)

# Display cleaned data
df_clean.head()

,question,answer
0,What is Artificial Intelligence?,Artificial Intelligence (AI) is the field of c...
1,What is an AI agent?,An AI agent is a system that perceives its env...
2,What is supervised AI?,Supervised AI usually refers to AI systems tra...
3,What is weak AI?,"Weak AI, or narrow AI, is designed to perform ..."
4,What is artificial general intelligence?,Artificial General Intelligence (AGI) is a hyp...

## STEP3 : Data Embedding and Model Deployment(Transformer)

In [14]:
!pip install sentence-transformers

Requirement already satisfied: sentence-transformers in c:\users\kshan\appdata\local\programs\python\python312\lib\site-packages (5.7.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in c:\users\kshan\appdata\local\programs\python\python312\lib\site-packages (from sentence-transformers) (5.5.0)
Requirement already satisfied: tokenizers>=0.19 in c:\users\kshan\appdata\local\programs\python\python312\lib\site-packages (from sentence-transformers) (0.22.2)
Requirement already satisfied: huggingface-hub>=0.23.0 in c:\users\kshan\appdata\local\programs\python\python312\lib\site-packages (from sentence-transformers) (1.9.0)
Requirement already satisfied: torch>=1.11.0 in c:\users\kshan\appdata\local\programs\python\python312\lib\site-packages (from sentence-transformers) (2.11.0)
Requirement already satisfied: numpy>=1.20.0 in c:\users\kshan\appdata\local\programs\python\python312\lib\site-packages (from sentence-transformers) (1.26.4)
Requirement already satisfied: scikit-learn>=0.22.0 in c:\users\kshan\appdata\local\programs\python\python312\lib\site-packages (from sentence-transformers) (1.8.0)
Requirement already satisfied: scipy>=1.0.0 in c:\users\kshan\appdata\local\programs\python\python312\lib\site-packages (from sentence-transformers) (1.17.0)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\users\kshan\appdata\local\programs\python\python312\lib\site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in c:\users\kshan\appdata\local\programs\python\python312\lib\site-packages (from sentence-transformers) (4.67.1)
Requirement already satisfied: filelock>=3.10.0 in c:\users\kshan\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\kshan\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2026.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\kshan\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\kshan\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in c:\users\kshan\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (24.1)
Requirement already satisfied: pyyaml>=5.1 in c:\users\kshan\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.2)
Requirement already satisfied: typer in c:\users\kshan\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.24.1)
Requirement already satisfied: joblib>=1.3.0 in c:\users\kshan\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\kshan\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools<82 in c:\users\kshan\appdata\local\programs\python\python312\lib\site-packages (from torch>=1.11.0->sentence-transformers) (73.0.1)
Requirement already satisfied: sympy>=1.13.3 in c:\users\kshan\appdata\local\programs\python\python312\lib\site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\kshan\appdata\local\programs\python\python312\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in c:\users\kshan\appdata\local\programs\python\python312\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: colorama in c:\users\kshan\appdata\local\programs\python\python312\lib\site-packages (from tqdm>=4.0.0->sentence-transformers) (0.4.6)
Requirement already satisfied: regex>=2025.10.22 in c:\users\kshan\appdata\local\programs\python\python312\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2026.2.19)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\kshan\appdata\local\programs\python\python312\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: anyio in c:\users\kshan\appdata\local\programs\python\python312\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.10.0)
Requirement already satisfied: certifi in c:\users\kshan\appdata\local\programs\python\python312\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.1.4)
Requirement already satisfied: httpcore==1.* in c:\users\kshan\appdata\local\programs\python\python312\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\kshan\appdata\local\programs\python\python312\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.8)
Requirement already satisfied: h11>=0.16 in c:\users\kshan\appdata\local\programs\python\python312\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\kshan\appdata\local\programs\python\python312\lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\kshan\appdata\local\programs\python\python312\lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (2.1.5)
Requirement already satisfied: click>=8.2.1 in c:\users\kshan\appdata\local\programs\python\python312\lib\site-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (8.3.0)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\kshan\appdata\local\programs\python\python312\lib\site-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in c:\users\kshan\appdata\local\programs\python\python312\lib\site-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (13.7.1)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\kshan\appdata\local\programs\python\python312\lib\site-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\kshan\appdata\local\programs\python\python312\lib\site-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\kshan\appdata\local\programs\python\python312\lib\site-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (2.18.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\kshan\appdata\local\programs\python\python312\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.3.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\kshan\appdata\local\programs\python\python312\lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (0.1.2)

[notice] A new release of pip is available: 24.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [15]:

from sentence_transformers import SentenceTransformer

# Load pretrained Sentence Transformer model
model = SentenceTransformer('all-MiniLM-L6-v2')

# Generate embeddings for all questions
question_embeddings = model.encode(
    df_clean['question'].tolist(),
    normalize_embeddings=True,
    show_progress_bar=True
)

# Check embedding shape
print("Embedding Shape:", question_embeddings.shape)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Embedding Shape: (200, 384)

## STEP5 : Testing Model and Cosine Similarity

In [16]:
# Import cosine similarity
from sklearn.metrics.pairwise import cosine_similarity

# Function for semantic question retrieval
def get_answer(user_question, threshold=0.55):

    # Convert user question into embedding
    query_embedding = model.encode(
        user_question,
        normalize_embeddings=True
    )

    # Calculate cosine similarity with all dataset questions
    similarity_scores = cosine_similarity(
        [query_embedding],
        question_embeddings
    )[0]

    # Find the index of the most similar question
    best_index = similarity_scores.argmax()

    # Get the highest similarity score
    best_score = similarity_scores[best_index]

    # Get the matching question and answer
    best_question = df_clean.iloc[best_index]['question']
    best_answer = df_clean.iloc[best_index]['answer']

    # Apply similarity threshold
    if best_score >= threshold:
        return best_question, best_answer, best_score
    else:
        return (
            None,
            "Sorry, I do not have information related to this question.",
            best_score
        )


# -------------------------------
# Test the chatbot
# -------------------------------

user_question = "Tell me something about linear regression."

best_question, answer, score = get_answer(user_question)

print("User Question:", user_question)
print("Best Matching Question:", best_question)
print("Similarity Score:", round(score, 4))
print("Answer:", answer)

User Question: Tell me something about linear regression.
Best Matching Question: What is linear regression?
Similarity Score: 0.8918
Answer: Linear regression models the relationship between input variables and a continuous target using a linear function.

## Hence , I have completed the project.